# Generated by Django 2.0.6 on 2018-06-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maintenanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maintenance Item Title', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Maintenance Item Description', max_length=100)),
                ('cfid', models.CharField(blank=True, help_text='Functional Description (i.e. HULL, CR-SPRT)', max_length=100)),
                ('periodicity', models.IntegerField(help_text='Time Inteval for Maintenance Item Period')),
                ('driver', models.CharField(choices=[('CMP-Conditional', 'CMP-Conditional'), ('CMP-Recurring', 'CMP-Recurring'), ('Conditional Task', 'Conditional Task'), ('Engineering Change', 'Engineering Change'), ('NONE', 'NONE'), ('Recurring Work Items', 'Recurring Work Item')], default='NONE', max_length=25)),
                ('fund_source', models.IntegerField(help_text='Funding Source')),
            ],
            options={
                'verbose_name': 'maintenance Item',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='maintenanceRequirementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'maintenance Requirement List',
            },
        ),
        migrations.CreateModel(
            name='productLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Line Name (e.g. LREPL, IBCTPL)', max_length=30)),
            ],
            options={
                'verbose_name': 'product Line',
            },
        ),
        migrations.CreateModel(
            name='shipClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ship Class Name (e.g WAGB, WTGB).', max_length=10)),
                ('productLine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apm.productLine', verbose_name='product Line')),
            ],
            options={
                'verbose_name_plural': 'ship Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='shipInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ship Name (e.g. POLAR STAR, MARIA BRAY)', max_length=50)),
                ('hull', models.IntegerField(help_text='Hull Number (e.g. 102, 555)')),
                ('availability', models.DateField(blank=True, help_text='Next Availability Date', null=True)),
                ('length', models.IntegerField(help_text='Ship Class Length (e.g. 100 foot ship).')),
                ('identifier', models.CharField(blank=True, help_text='Ship Class Identifier defaults to length - name (e.g. 175-WLM)', max_length=30, verbose_name='Description')),
                ('shipClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apm.shipClass', verbose_name='Ship Class')),
            ],
            options={
                'verbose_name': 'ship Instance',
                'ordering': ['hull'],
            },
        ),
        migrations.CreateModel(
            name='supplyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIIN', models.CharField(help_text='USCG NIIN Number', max_length=30)),
                ('PN', models.CharField(help_text='Part Number', max_length=30)),
                ('FSC', models.CharField(help_text='Part Location?', max_length=10)),
                ('itemDescription', models.CharField(blank=True, help_text='Item Description', max_length=100)),
                ('maintenanceItem', models.ManyToManyField(blank=True, help_text='Applicable Maintenance Item', to='apm.maintenanceItem')),
            ],
            options={
                'verbose_name': 'supply Part',
                'ordering': ['PN'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequirementlist',
            name='shipInstance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apm.shipInstance', verbose_name='Ship Instance'),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='maintenanceRequirementList',
            field=models.ManyToManyField(blank=True, help_text='Applicable Maintenance Requirement List', to='apm.maintenanceRequirementList'),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='shipInstance',
            field=models.ManyToManyField(help_text='Applicable Ship', to='apm.shipInstance'),
        ),
    ]
